xtd::network::http::Server::Handler::filter
typedef boost::function<bool (const Request&)> xtd::network::http::Server< TDomain >::Handler::filter::t_func
xtd::network::http::Server< TDomain >::Handler::filter::filter(void)
Referenced by xtd::network::http::Server< TDomain >::Handler::filter::operator||, xtd::network::http::Server< TDomain >::Handler::filter::operator&&, xtd::network::http::Server< TDomain >::Handler::filter::operator!.
xtd::network::http::Server< TDomain >::Handler::filter::filter(A p_method)
xtd::network::http::Server< TDomain >::Handler::filter::filter(A p_method, Base p_instance)
xtd::network::http::Server< TDomain >::Handler::filter::filter(A p_method, Base p_instance, B p_arg1)
xtd::network::http::Server< TDomain >::Handler::filter::filter(A p_method, Base p_instance, B p_arg1, C p_arg2)
xtd::network::http::Server< TDomain >::Handler::filter::filter(A p_method, Base p_instance, B p_arg1, C p_arg2, D p_arg3)
filter xtd::network::http::Server< TDomain >::Handler::filter::operator||(filter p_filter2)
References xtd::network::http::Server< TDomain >::Handler::filter::filter.
filter xtd::network::http::Server< TDomain >::Handler::filter::operator&&(filter p_filter2)
References xtd::network::http::Server< TDomain >::Handler::filter::filter.
filter xtd::network::http::Server< TDomain >::Handler::filter::operator!(void)
References xtd::network::http::Server< TDomain >::Handler::filter::filter.